displayName: hpc01Name
slurm:
  loginNodes:
      - address: localhost
      - port: 22222
      - keypath: ~/.ssh/id_rsa
  partitions:
      - name: compute
        nodes: 3
        mem: 262144
        cores: 32
        gpus: 0
        qos:
          - low
          - normal
          - high
        comment: 说明

      - name: GPU
        nodes: 1
        mem: 262144
        cores: 48
        gpus: 8
        qos:
          - low
          - normal
          - high
          - highest
        comment: 说明
