displayName: hpc01
# adapterUrl: 0.0.0.0:6000
adapterUrl: "192.168.88.101:8972"
# loginNodes:
#   - name: login
#     address: localhost:22222
loginNodes:
  # 登录节点展示名称
  - name: login
    # 登录节点的IP或者域名
    # 如果设置的是域名，请确认此节点的/etc/hosts中包含了域名到IP的解析信息
    address: 192.168.88.102
# misIgnore: true
# slurm:
#   mis:
#     managerUrl: localhost:22222
#     dbPassword: password
#     clusterName: pkuhpc1
#     scriptPath: /slurmshTest/slurm.sh
#   loginNodes:
#     - localhost:22222
#   partitions:
#     - name: compute
#       nodes: 198
#       mem: 63000
#       cores: 28
#       gpus: 0
#       qos:
#         - low
#         - normal
#         - high
#     - name: gpu
#       nodes: 1
#       mem: 386000
#       cores: 48
#       gpus: 8
#       qos:
#         - low
#         - normal
#         - high
