db:
  host: localhost
  port: 3306
  user: root
  password: mysqlrootpassword
  dbName: scow_server_${JEST_WORKER_ID}

periodicSyncUserAccountBlockStatus:
  enabled: false

deleteUser:
  enabled: true
  nameMarker: "(已删除)"

deleteAccount:
  enabled: true
