# 这个应用的ID
id: ShadowDesk

# 这个应用的名字
name: ShadowDesk

# 指定应用类型为shadowDesk
type: shadowDesk

# 可以运行这个应用的节点地址。
# 如果不设置nodes，则所有节点都可以运行
#nodes:
#  - cn1
#  - cn2
#  - cn3
#  - cn4

logoPath: /apps/shadowdesk.png

# shadowDesk应用的配置
shadowDesk:
  # 准备脚本
  beforeScript: |
    export PORT=$(get_port)
    export PASSWORD=$(get_password 12)
    export SLURM_COMPUTE_NODE_HOSTNAME=$(hostname)
    export PATH=$PATH:/data/software/singularity/3.9.2/bin
    export SIF_PATH=/data/software/shadowdesk/sd-backend.sif
    export SIGNALLING_URL=ws://172.16.20.146:8765/shadowdesk/ws

  # 运行任务的脚本。可以使用准备脚本定义的
  script: |
    function get_port1 {
       echo $(python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()')
    }
    # export BASEURL="${PROXY_BASE_PATH}/${SLURM_COMPUTE_NODE_HOSTNAME}/${SS_PORT}"
    singularity exec --writable-tmpfs --env LOGGER_LEVEL=1 --env SCREEN_RESOLUTION=1920x1080x24 --env SIGNALLING_URL=${SIGNALLING_URL} --env USER_ID=${USER} --env USER_PASSWORD=${PASSWORD} --env ENCODER=x264enc --env VIDEO_FORMAT=Y444 --env ENABLE_AUDIO=true --env VIDEO_PORT=DFP --env SIZEW=1920 --env SIZEH=1080 --env REFRESH=60 --env CDEPTH=24 --env DPI=96 ${SIF_PATH} bash -c 'start_backend.sh'

  proxyType: relative
  proxyServer: 172.16.20.146:8765

  # 改relative
  # 如何连接应用 path直接可以拼在scow后+shadowdesk，也可以完全外部url。如果是http或者https，就直接连外面。如果不是就直接拼在scow的url下面。
  connect:
    method: POST
    path: /login
    formData:
      id: "{{ USER }}"
      password: "{{ PASSWORD }}"

attributes:
  - type: text
    name: sbatchOptions
    # label: 其他sbatch参数
    label:
      i18n:
        default: 其他sbatch参数
        en: Other sbatch parameters
        zh_cn: 其他sbatch参数
    required: false
    # placeholder: "比如：--gpus gres:2 --time 10"
    placeholder:
      i18n:
        default: "比如：--gpus gres:2 --time 10"
        en: "For example: --gpus gres:2 --time 10"
        zh_cn: "比如：--gpus gres:2 --time 10"
