db:
  host: localhost
  port: 3306
  user: root
  password: mysqlrootpassword
  dbName: scow_notification

redis:
  enabled: true
  host: localhost
  port: 6379

scow:
  misServerUrl: http://localhost:5004

noticeType:
  siteMessage:
    enabled: true
  email:
    enabled: true

log:
  level: info
  pretty: false

