db:
  host: localhost
  port: 3306
  user: root
  password: mysqlrootpassword
  dbName: scow_notification

redis:
  enabled: true
  host: localhost
  port: 6379

scow:
  misServerUrl: localhost:5004

noticeType:
  siteMessage:
    enabled: true
  email:
    enabled: true

log:
  level: info
  pretty: false

# messageBridge:
#   address: http://localhost:3000

deleteExpiredMessages:
  cron: "0 3 * * *"


