name: Test, Build and Publish Projects

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    tags:
      - "v**"
      - "ai-beta.**"
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  GITHUB_CR: ghcr.io

jobs:
  test-version-packages:
    name: Test and version packages
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          # changelog generation requires full history
          # to track each changelog file to its submission commit
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: pnpm/action-setup@v4.0.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: build
        run: bash build-scow.sh

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: scow-dist
          path: scow-dist.tgz
