name: Tag a release
on:
  push:
    paths:
      - package.json
    branches:
      - "master"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  tag-if-needed:
    runs-on: ${{ vars.ACTION_RUNNER_LABEL }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          # Must use a PAT instead of GITHUB_TOKEN
          # Events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run.
          # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
          token: ${{ secrets.RELEASE_GITHUB_PAT }}
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Create tag if needed
        run: node scripts/tag.mjs
