jobs:
  build-images:
    needs: test-version-packages
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - name: scow
            file: scow
            build_args: ""

          - name: docs
            file: docs
            build_args: BASE_PATH=/SCOW/

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@7840e6ddd4a9223910798f6a315544257fccd96e
        with:
          registry: ${{ env.GITHUB_CR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GITHUB_CR }}/${{ github.repository }}/${{ matrix.name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: ${{ matrix.build_args }}
          tags: ${{ steps.meta.outputs.tags }}
          file: docker/Dockerfile.${{ matrix.file }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64/v8  # Always build for both amd64 and arm64
